### ISSUE TITLE
Questions about data split

### ISSUE THREAD

**Issue by atusi-nakajima** [Deepthi-Jallepalli/CMPE-295A-Master-Project#2]
Please let me know if there are a few things I don't understand.
Currently I have downloaded the dataset from the official kitti website. (The two files I downloaded are as follows. Is this correct?
[on this site](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark)
・Download left color images of object data set (12 GB) (data_object_image_2.zip)
・Download training labels of object data set (5 MB) (data_object_label_2.zip))

Then I extracted them in the same directory.
The directory structure is as follows
.
├── testing
│   　　└── image_2
└── training
　　 　├── image_2
　　　 └── label_2

How can I then convert the data to yolo and do the data split?
I checked the code in data_split.py, but I don't think it includes the conversion to yolo.
Could you please explain in as much detail as possible the steps for converting to yolo and data split?
Thank you in advance.

**Comment by xierongpytorch** [comment]
> Please let me know if there are a few things I don't understand. Currently I have downloaded the dataset from the official kitti website. (The two files I downloaded are as follows. Is this correct? [on this site](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark) ・Download left color images of object data set (12 GB) (data_object_image_2.zip) ・Download training labels of object data set (5 MB) (data_object_label_2.zip))
> 
> Then I extracted them in the same directory. The directory structure is as follows . ├── testing │ 　　└── image_2 └── training 　　 　├── image_2 　　　 └── label_2
> 
> How can I then convert the data to yolo and do the data split? I checked the code in data_split.py, but I don't think it includes the conversion to yolo. Could you please explain in as much detail as possible the steps for converting to yolo and data split? Thank you in advance.

Hi~ I also encountered the same problem, have you solved it? 

I ran python server_rec_weights.py and it appeared
 =======Executing Server side round 0 communication=======; 

I ran python client_send_weights.py, appeared 
======= Training completed successfully ===========
File path /CMPE-295A-Master-Project/checkpoints/yolov3_custom.data-00000-of-00001
Send file: /CMPE-295A-Master-Project/checkpoints/yolov3_custom.data-00000-of-00001 , size: 246534511
Send encrypted file size = 328712760
Traceback (most recent call last):
  File "client_send_weights.py", line 59, in <module>
    sbuf.secure_send_file(full_filename)
  File "/CMPE-295A-Master-Project/buffer.py", line 78, in secure_send_file
    self.put_utf8(str(len(cipherText)))
  File "/CMPE-295A-Master-Project/buffer.py", line 106, in put_utf8
    self.sock.sendall(cipherText + b'\x00')
BrokenPipeError: [Errno 32] Broken pipe. 

I changed some paths but I am still not sure if I am correct.
I hope to ask for help~
